### PR TITLE
feat: edgejs support

### PR DESCRIPTION
**Pull request by Wilovy09**
I'm not sure if that's enough to support it, but I think it is.
Also it would be nice to support [edgejs](https://edgejs.dev/docs/introduction)
Zed won't let me open the dev extensions because of portals in linux.

### CODE REVIEW

**Comment by xhyrom** [comment]
i think this is enough. thanks!

**Comment by Wilovy09** [comment]
@xhyrom I'm working on supporting Edgejs, I've just never done it before so I need to learn it.

**Comment by Wilovy09** [comment]
@xhyrom Will this be enough?
Repo: https://github.com/Wilovy09/zed-edgejs
image

**Comment by xhyrom** [comment]
Yeah! I'll add it today.

PS: don't forget to also add this extension to official https://github.com/zed-extensions/extensions

**Pull request merged**
